# Client groups
rest_server1_clients: [vish,shabari]
rest_server2_clients: [priyal,neil]

#Redis server details:
redis_server:
    hostname: localhost
    port: 6000

one:
 hostname: localhost
 server_port : 3000
 connection_port : [4000]

two:
  hostname: localhost
  server_port : 4000
  connection_port : [3000]

three:
  hostname: localhost
  server_port: 5000
  connection_port: [3000]