# Client groups
rest_server1_clients: [vish,shabari]
rest_server2_clients: [priyal,neil]

one:
 hostname: localhost
 rest_server_port: 3000
 server_port : 3001
 connection_port : [4001]
 primary : 1

two:
 hostname: localhost
 rest_server_port: 4000
 server_port : 4001
 connection_port : [3001]
 primary : 0


three:
 hostname: localhost
 rest_server_port: 5000
 server_port : 5001
 connection_port : [4001]
 primary : 0
